apiVersion: apps/v1
kind: Deployment
metadata:
  name: cargo2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cargo2
  template:
    metadata:
      labels:
        app: cargo2
    spec:
      containers:
      - name: cargo2
        image: gcr.io/easytraining-413521/cargo1:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cargo2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: cargo2



